apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-operator
  name: auth-operator
  namespace: auth-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-operator
        prefer_run_on_fargate: 'true'
      namespace: kube-system
    spec:
      automountServiceAccountToken: true
      serviceAccount: auth-operator
      containers:
        - args:
            - --verbose
            - --liveness=http://0.0.0.0:8080/healthz
            - --standalone
          image: dcodetech/aws_auth_eks_crd:1.1.8
          imagePullPolicy: IfNotPresent
          name: operator
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 900
            timeoutSeconds: 30
